[project]
name = "comfyui-vrm-pose-editor"
description = "ComfyUI custom node for interactive 3D pose editing with VRM / GLB / GLTF support"
version = "0.13.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/ketle-man/comfyui-vrm-pose-editor"

[tool.comfy]
PublisherId = "statsu"
DisplayName = "comfyui-vrm-pose-editor"
Icon = "https://raw.githubusercontent.com/ketle-man/comfyui-vrm-pose-editor/master/docs/thumb.png"
